# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autores',
            field=models.ManyToManyField(null=True, related_name='autores_id', to='blog.Autor'),
        ),
    ]
