# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='doing',
            field=models.ManyToManyField(related_name='doing_id', to='scrum_board.Card'),
        ),
        migrations.AddField(
            model_name='board',
            name='done',
            field=models.ManyToManyField(related_name='done_id', to='scrum_board.Card'),
        ),
        migrations.AddField(
            model_name='board',
            name='todo',
            field=models.ManyToManyField(related_name='todo_id', to='scrum_board.Card'),
        ),
        migrations.AlterField(
            model_name='board',
            name='back_log',
            field=models.ManyToManyField(related_name='backlog_id', to='scrum_board.Card'),
        ),
    ]
